import React, { useState } from "react";

// Supported Indian languages
const INDIAN_LANGUAGES = [
  { code: "hi", name: "Hindi", native: "हिंदी" },
  { code: "bn", name: "Bengali", native: "বাংলা" },
  { code: "ta", name: "Tamil", native: "தமிழ்" },
  { code: "te", name: "Telugu", native: "తెలుగు" },
  { code: "kn", name: "Kannada", native: "ಕನ್ನಡ" },
  { code: "ml", name: "Malayalam", native: "മലയാളം" },
  { code: "mr", name: "Marathi", native: "मराठी" },
  { code: "gu", name: "Gujarati", native: "ગુજરાતી" },
  { code: "pa", name: "Punjabi", native: "ਪੰਜਾਬੀ" },
  { code: "ur", name: "Urdu", native: "اردو" },
  { code: "or", name: "Odia", native: "ଓଡ଼ିଆ" },
  { code: "as", name: "Assamese", native: "অসমীয়া" },
  { code: "en", name: "English", native: "English" },
];

const GRADE_LEVELS = [
  { value: "3", label: "Class 3" },
  { value: "8", label: "Class 8" },
  { value: "12", label: "Class 12" },
  { value: "custom", label: "Custom" },
];

const SUBJECTS = [
  { value: "mathematics", label: "Mathematics", icon: "📐" },
  { value: "science", label: "Science", icon: "🔬" },
  { value: "social", label: "Social Studies", icon: "🌍" },
  { value: "language", label: "Language", icon: "📚" },
];

const CURRICULUMS = [
  { value: "ncert", label: "NCERT" },
  { value: "cbse", label: "CBSE" },
  { value: "state", label: "State Board" },
];

interface LaTeXPreviewProps {
  latexCode: string;
}

const LaTeXPreview: React.FC<LaTeXPreviewProps> = ({ latexCode }) => {
  if (!latexCode) {
    return (
      <div className="flex items-center justify-center h-full text-gray-400">
        <div className="text-center">
          <svg
            className="w-16 h-16 mx-auto mb-4 text-gray-300"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"
            />
          </svg>
          <p className="text-sm">LaTeX preview will appear here</p>
        </div>
      </div>
    );
  }

  return (
    <div className="h-full overflow-auto p-4 bg-white">
      <div className="prose max-w-none">
        {/* Placeholder for LaTeX rendering - will use MathJax/KaTeX */}
        <div className="border-2 border-dashed border-gray-300 rounded-lg p-6 bg-gray-50">
          <pre className="whitespace-pre-wrap text-xs font-mono text-gray-700 mb-4">
            {latexCode}
          </pre>
          <div className="text-sm text-gray-500 italic">
            Note: LaTeX rendering preview will be implemented with MathJax/KaTeX
          </div>
        </div>
      </div>
    </div>
  );
};

const StitchPage: React.FC = () => {
  const [selectedLanguage, setSelectedLanguage] = useState("hi");
  const [selectedGrade, setSelectedGrade] = useState("8");
  const [selectedSubject, setSelectedSubject] = useState("mathematics");
  const [selectedCurriculum, setSelectedCurriculum] = useState("ncert");
  const [topic, setTopic] = useState("");
  const [culturalContext, setCulturalContext] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [latexCode, setLatexCode] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [chatHistory, setChatHistory] = useState<
    Array<{ role: "user" | "assistant"; content: string }>
  >([]);

  const handleGenerate = async () => {
    if (!topic.trim()) {
      setError("Please enter a topic");
      return;
    }

    setIsGenerating(true);
    setError(null);

    // Add user message to chat
    const userMessage = `Generate content for: ${topic} (${selectedSubject}, ${INDIAN_LANGUAGES.find(l => l.code === selectedLanguage)?.name}, Class ${selectedGrade}, ${CURRICULUMS.find(c => c.value === selectedCurriculum)?.label})`;
    setChatHistory((prev) => [...prev, { role: "user", content: userMessage }]);

    try {
      // TODO: Integrate with Ollama API for offline LLM
      // For now, generate placeholder LaTeX
      const placeholderLatex = `\\documentclass[12pt]{article}
\\usepackage[utf8]{inputenc}
\\usepackage{amsmath}
\\usepackage{amsfonts}
\\usepackage{amssymb}

\\title{${topic}}
\\author{Generated by Stitch}
\\date{\\today}

\\begin{document}

\\maketitle

\\section{Introduction}
This is a placeholder LaTeX document for ${topic} in ${INDIAN_LANGUAGES.find(l => l.code === selectedLanguage)?.name}.

\\section{Main Content}
Content will be generated here using offline LLM (Ollama + DeepSeek).

\\section{Conclusion}
This document demonstrates the LaTeX generation capability of Stitch.

\\end{document}`;

      setLatexCode(placeholderLatex);
      setChatHistory((prev) => [
        ...prev,
        {
          role: "assistant",
          content: "LaTeX content generated successfully. Preview available below.",
        },
      ]);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to generate content");
      setChatHistory((prev) => [
        ...prev,
        {
          role: "assistant",
          content: "Error: Failed to generate content. Please try again.",
        },
      ]);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleGeneratePDF = () => {
    if (!latexCode) {
      setError("No LaTeX code to compile. Please generate content first.");
      return;
    }

    // TODO: Implement PDF generation via backend LaTeX compiler
    alert("PDF generation will be implemented with backend LaTeX compiler");
  };

  const handleEdit = (newContent: string) => {
    // TODO: Send edit request to LLM and regenerate
    alert("Edit functionality will be implemented");
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-orange-50 to-white">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6 sm:py-8">
        {/* Header */}
        <div className="mb-8 text-center">
          <h1 className="text-3xl sm:text-4xl md:text-5xl font-semibold text-gray-800 mb-3">
            <span className="text-orange-400">Stitch</span> - Offline Multilingual
            Content Generator
          </h1>
          <p className="text-sm sm:text-base md:text-lg text-gray-600 max-w-3xl mx-auto">
            Generate curriculum-aligned educational content in 22+ Indian languages
            using offline LLM (Ollama + DeepSeek) with LaTeX rendering
          </p>
        </div>

        {/* Main Content Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 mb-6">
          {/* Left Panel - Configuration */}
          <div className="lg:col-span-1 space-y-4">
            <div className="bg-white rounded-xl shadow-lg p-6">
              <h2 className="text-xl font-semibold text-gray-800 mb-4">
                Configuration
              </h2>

              {/* Language Selector */}
              <div className="mb-4">
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Language
                </label>
                <select
                  value={selectedLanguage}
                  onChange={(e) => setSelectedLanguage(e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-orange-400 focus:border-orange-400"
                >
                  {INDIAN_LANGUAGES.map((lang) => (
                    <option key={lang.code} value={lang.code}>
                      {lang.name} ({lang.native})
                    </option>
                  ))}
                </select>
              </div>

              {/* Grade Level */}
              <div className="mb-4">
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Grade Level
                </label>
                <select
                  value={selectedGrade}
                  onChange={(e) => setSelectedGrade(e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-orange-400 focus:border-orange-400"
                >
                  {GRADE_LEVELS.map((grade) => (
                    <option key={grade.value} value={grade.value}>
                      {grade.label}
                    </option>
                  ))}
                </select>
              </div>

              {/* Subject Selector */}
              <div className="mb-4">
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Subject
                </label>
                <div className="grid grid-cols-2 gap-2">
                  {SUBJECTS.map((subject) => (
                    <button
                      key={subject.value}
                      onClick={() => setSelectedSubject(subject.value)}
                      className={`px-4 py-2 rounded-lg border-2 transition-all ${
                        selectedSubject === subject.value
                          ? "border-orange-400 bg-orange-50 text-orange-600"
                          : "border-gray-200 hover:border-gray-300 text-gray-700"
                      }`}
                    >
                      <span className="mr-2">{subject.icon}</span>
                      {subject.label}
                    </button>
                  ))}
                </div>
              </div>

              {/* Curriculum */}
              <div className="mb-4">
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Curriculum
                </label>
                <select
                  value={selectedCurriculum}
                  onChange={(e) => setSelectedCurriculum(e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-orange-400 focus:border-orange-400"
                >
                  {CURRICULUMS.map((curriculum) => (
                    <option key={curriculum.value} value={curriculum.value}>
                      {curriculum.label}
                    </option>
                  ))}
                </select>
              </div>

              {/* Topic Input */}
              <div className="mb-4">
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Topic / Lesson Title
                </label>
                <input
                  type="text"
                  value={topic}
                  onChange={(e) => setTopic(e.target.value)}
                  placeholder="e.g., Photosynthesis, Quadratic Equations"
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-orange-400 focus:border-orange-400"
                />
              </div>

              {/* Cultural Context Toggle */}
              <div className="mb-4">
                <label className="flex items-center">
                  <input
                    type="checkbox"
                    checked={culturalContext}
                    onChange={(e) => setCulturalContext(e.target.checked)}
                    className="w-4 h-4 text-orange-400 border-gray-300 rounded focus:ring-orange-400"
                  />
                  <span className="ml-2 text-sm text-gray-700">
                    Include cultural context
                  </span>
                </label>
              </div>

              {/* Generate Button */}
              <button
                onClick={handleGenerate}
                disabled={isGenerating || !topic.trim()}
                className="w-full bg-orange-400 text-white px-6 py-3 rounded-lg font-semibold hover:bg-orange-500 transition-all shadow-md hover:shadow-lg disabled:bg-gray-300 disabled:cursor-not-allowed"
              >
                {isGenerating ? "Generating..." : "Generate Content"}
              </button>

              {/* Error Display */}
              {error && (
                <div className="mt-4 p-3 bg-red-50 border border-red-200 rounded-lg text-sm text-red-600">
                  {error}
                </div>
              )}
            </div>

            {/* Ollama Status */}
            <div className="bg-white rounded-xl shadow-lg p-4">
              <div className="flex items-center justify-between">
                <span className="text-sm font-medium text-gray-700">
                  Ollama Status
                </span>
                <span className="px-2 py-1 bg-yellow-100 text-yellow-800 rounded text-xs">
                  Not Connected
                </span>
              </div>
              <p className="text-xs text-gray-500 mt-2">
                Connect to Ollama for offline LLM
              </p>
            </div>
          </div>

          {/* Right Panel - Chat Interface with Preview */}
          <div className="lg:col-span-2 space-y-4">
            {/* Chat Interface */}
            <div className="bg-white rounded-xl shadow-lg h-64 overflow-y-auto p-4">
              <h3 className="text-lg font-semibold text-gray-800 mb-3">
                Generation Log
              </h3>
              {chatHistory.length === 0 ? (
                <div className="flex items-center justify-center h-full text-gray-400">
                  <p className="text-sm">Your generation history will appear here</p>
                </div>
              ) : (
                <div className="space-y-3">
                  {chatHistory.map((message, index) => (
                    <div
                      key={index}
                      className={`flex ${
                        message.role === "user" ? "justify-end" : "justify-start"
                      }`}
                    >
                      <div
                        className={`max-w-[80%] rounded-lg p-3 ${
                          message.role === "user"
                            ? "bg-orange-400 text-white"
                            : "bg-gray-100 text-gray-800"
                        }`}
                      >
                        <p className="text-sm">{message.content}</p>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>

            {/* LaTeX Preview */}
            <div className="bg-white rounded-xl shadow-lg h-96 flex flex-col">
              <div className="flex items-center justify-between p-4 border-b border-gray-200">
                <h3 className="text-lg font-semibold text-gray-800">
                  LaTeX Preview
                </h3>
                <div className="flex gap-2">
                  <button
                    onClick={() => handleEdit("")}
                    className="px-4 py-2 text-sm border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors"
                  >
                    Edit
                  </button>
                  <button
                    onClick={handleGeneratePDF}
                    disabled={!latexCode}
                    className="px-4 py-2 text-sm bg-orange-400 text-white rounded-lg hover:bg-orange-500 transition-all disabled:bg-gray-300 disabled:cursor-not-allowed"
                  >
                    Generate PDF
                  </button>
                </div>
              </div>
              <div className="flex-1 overflow-hidden">
                <LaTeXPreview latexCode={latexCode} />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default StitchPage;
