export { default as DottedBackground } from "./background/DottedBackground"
export { default as CanvasDock, type EraserMode } from "./dock/CanvasDock"
export { default as StickyNote } from "./tools/StickyNote"
export { default as TextBox } from "./tools/TextBox"
export * from "./tools"
